name: openthesaurus_cli
description: An cross platform [openthesaurus](https://openthesaurus.de) command line application.
version: 1.0.0
repository: https://github.com/hayribakici/openthesaurus-cli

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  openthesaurus: 0.0.5
  args: ^2.4.2
  chalkdart: ^2.0.9
  compile: ^0.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables: 
  compile:
